export const commonVerbs = [
  { value: "say", label: "say", translation: "говорить, сказать", v2: "said", v3: "said" },
  { value: "go", label: "go", translation: "идти, ехать", v2: "went", v3: "gone" },
  { value: "get", label: "get", translation: "получать", v2: "got", v3: "got/gotten" },
  { value: "make", label: "make", translation: "делать, создавать", v2: "made", v3: "made" },
  { value: "know", label: "know", translation: "знать", v2: "knew", v3: "known" },
  { value: "think", label: "think", translation: "думать", v2: "thought", v3: "thought" },
  { value: "take", label: "take", translation: "брать", v2: "took", v3: "taken" },
  { value: "see", label: "see", translation: "видеть", v2: "saw", v3: "seen" },
  { value: "come", label: "come", translation: "приходить", v2: "came", v3: "come" },
  { value: "want", label: "want", translation: "хотеть", v2: "wanted", v3: "wanted" },
  { value: "look", label: "look", translation: "смотреть", v2: "looked", v3: "looked" },
  { value: "use", label: "use", translation: "использовать", v2: "used", v3: "used" },
  { value: "find", label: "find", translation: "находить", v2: "found", v3: "found" },
  { value: "give", label: "give", translation: "давать", v2: "gave", v3: "given" },
  { value: "tell", label: "tell", translation: "рассказывать", v2: "told", v3: "told" },
  { value: "work", label: "work", translation: "работать", v2: "worked", v3: "worked" },
  { value: "call", label: "call", translation: "звонить, называть", v2: "called", v3: "called" },
  { value: "try", label: "try", translation: "пытаться", v2: "tried", v3: "tried" },
  { value: "ask", label: "ask", translation: "спрашивать", v2: "asked", v3: "asked" },
  { value: "need", label: "need", translation: "нуждаться", v2: "needed", v3: "needed" },
  { value: "feel", label: "feel", translation: "чувствовать", v2: "felt", v3: "felt" },
  { value: "become", label: "become", translation: "становиться", v2: "became", v3: "become" },
  { value: "leave", label: "leave", translation: "уходить", v2: "left", v3: "left" },
  { value: "put", label: "put", translation: "класть", v2: "put", v3: "put" },
  { value: "mean", label: "mean", translation: "значить", v2: "meant", v3: "meant" },
  { value: "keep", label: "keep", translation: "держать", v2: "kept", v3: "kept" },
  { value: "let", label: "let", translation: "позволять", v2: "let", v3: "let" },
  { value: "begin", label: "begin", translation: "начинать", v2: "began", v3: "begun" },
  { value: "seem", label: "seem", translation: "казаться", v2: "seemed", v3: "seemed" },
  { value: "help", label: "help", translation: "помогать", v2: "helped", v3: "helped" },
  { value: "talk", label: "talk", translation: "разговаривать", v2: "talked", v3: "talked" },
  { value: "turn", label: "turn", translation: "поворачивать", v2: "turned", v3: "turned" },
  { value: "start", label: "start", translation: "начинать", v2: "started", v3: "started" },
  { value: "show", label: "show", translation: "показывать", v2: "showed", v3: "shown" },
  { value: "hear", label: "hear", translation: "слышать", v2: "heard", v3: "heard" },
  { value: "play", label: "play", translation: "играть", v2: "played", v3: "played" },
  { value: "run", label: "run", translation: "бежать", v2: "ran", v3: "run" },
  { value: "move", label: "move", translation: "двигаться", v2: "moved", v3: "moved" },
  { value: "like", label: "like", translation: "нравиться", v2: "liked", v3: "liked" },
  { value: "live", label: "live", translation: "жить", v2: "lived", v3: "lived" },
  { value: "believe", label: "believe", translation: "верить", v2: "believed", v3: "believed" },
  { value: "hold", label: "hold", translation: "держать", v2: "held", v3: "held" },
  { value: "bring", label: "bring", translation: "приносить", v2: "brought", v3: "brought" },
  { value: "happen", label: "happen", translation: "происходить", v2: "happened", v3: "happened" },
  { value: "write", label: "write", translation: "писать", v2: "wrote", v3: "written" },
  { value: "sit", label: "sit", translation: "сидеть", v2: "sat", v3: "sat" },
  { value: "stand", label: "stand", translation: "стоять", v2: "stood", v3: "stood" },
  { value: "lose", label: "lose", translation: "терять", v2: "lost", v3: "lost" },
  { value: "pay", label: "pay", translation: "платить", v2: "paid", v3: "paid" },
  { value: "meet", label: "meet", translation: "встречать", v2: "met", v3: "met" },
  { value: "learn", label: "learn", translation: "учиться", v2: "learned/learnt", v3: "learned/learnt" },
  { value: "understand", label: "understand", translation: "понимать", v2: "understood", v3: "understood" },
  { value: "speak", label: "speak", translation: "говорить", v2: "spoke", v3: "spoken" },
  { value: "read", label: "read", translation: "читать", v2: "read", v3: "read" },
  { value: "buy", label: "buy", translation: "покупать", v2: "bought", v3: "bought" },
  { value: "send", label: "send", translation: "отправлять", v2: "sent", v3: "sent" },
  { value: "build", label: "build", translation: "строить", v2: "built", v3: "built" },
  { value: "stay", label: "stay", translation: "оставаться", v2: "stayed", v3: "stayed" },
  { value: "fall", label: "fall", translation: "падать", v2: "fell", v3: "fallen" },
  { value: "cut", label: "cut", translation: "резать", v2: "cut", v3: "cut" },
  { value: "sell", label: "sell", translation: "продавать", v2: "sold", v3: "sold" },
  { value: "teach", label: "teach", translation: "учить", v2: "taught", v3: "taught" },
  { value: "catch", label: "catch", translation: "ловить", v2: "caught", v3: "caught" },
  { value: "choose", label: "choose", translation: "выбирать", v2: "chose", v3: "chosen" }
];

export const pronouns = ["I", "you", "we", "they", "he", "she"];
